[tool.black]
line-length = 110
target-version = ['py38']

[tool.poetry]
name = 'shifter-pandas'
version = '0.0.0'
description = 'Not used'
authors = []

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
requests = "2.*"
pandas = "1.*"
openpyxl = "3.*"
wikidata = "0.7.*"

[tool.poetry.dev-dependencies]
prospector = {version = "1.7.*", extras = ["with_bandit", "with_mypy", "with_pyroma"]}
pylint = "2.13.*"
pytest = "7.*"
coverage = "6.*"
types-toml = "0.10.*"
types-requests = "2.*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
