[tool.black]
line-length = 110
target-version = ["py38"]

[tool.isort]
known_first_party = ["shifter_pandas"]
known_third_party = []
multi_line_output = 3
include_trailing_comma = 1
force_grid_wrap = 0
use_parentheses = 1
line_length = 110
force_sort_within_sections = 1

[tool.mypy]
python_version = 3.8
ignore_missing_imports = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
strict = true
exclude = "setup.py"

[tool.poetry]
name = "shifter-pandas"
version = "0.0.0"
description = "Convert some data into Panda DataFrames"
readme = "README.md"
authors = ["Stéphane Brunner <stephane.brunner@gmail.com>"]
homepage = "https://hub.docker.com/r/sbrunner/shifter-pandas/"
repository = "https://github.com/sbrunner/shifter-pandas"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Typing :: Typed",
]
keywords = ["shifter", "pandas"]
packages = [{ include = "shifter_pandas" }, { include = "shifter_pandas/py.typed" }]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
requests = "2.28.1"
pandas = "1.5.2"
openpyxl = "3.0.10"
wikidata = "0.7.0"
toml = "0.10.2"
certifi = "2022.12.7"

[tool.poetry.dev-dependencies]
prospector = { version = "1.7.7", extras = ["with_bandit", "with_mypy", "with_pyroma"] }
pytest = "7.2.0"
coverage = "6.5.0"
types-toml = "0.10.8.1"
types-requests = "2.28.11.5"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-plugin-tweak-dependencies-version", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-plugin-tweak-dependencies-version]
default = "present"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"
pattern = "^((?P<epoch>\\d+)!)?(?P<base>\\d+(\\.\\d+)*)"
