[tool.black]
line-length = 110
target-version = ['py38']

[tool.poetry]
name = 'shifter_poetry'
version = '0.0.0'
description = 'Not used'
authors = []

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
"requests" = "2.*"
"panda" = "0.3.*"

[tool.poetry.dev-dependencies]
prospector = {version = "1.*", extras = ["with_bandit", "with_mypy", "with_pyroma"]}
pylint = "2.11.*"
pytest = "7.*"
coverage = "6.*"
types-toml = "0.10.*"
