# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/master/c2cciutils/schema.json

checks:
  codespell:
    ignore_re:
      - poetry\.lock
      - shifter_pandas/wikidata_\.py
      - tests/test_get_region\.py
  black:
    ignore_patterns_re:
      - README\.md
  setup: false
